version: '3'
services:
  app:
    build: .
    ports:
      - "65413:65413"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:65413"]
      interval: 10s
      timeout: 5s
      retries: 5

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: >
      sh -c "sleep 20 && zap-baseline.py -t http://app:8000 -J /zap/wrk/zap-report.json -I"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./zap-reports:/zap/wrk
